### ISSUE TITLE
readme.md

### ISSUE THREAD

**Issue by VietTran0302** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst.zh-cn#1]
English:
Microsoft Power BI Data Analyst

Current Translation:
Microsoft Power BI 資料分析師

Suggested Translation:
Microsoft Power BI 数据分析师

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by stonezy123** [comment]
Run the bugfix tool and waiting for result.[ ICMS QUERY](https://wus-000.icms.osi.office.net/vantagepoint/QueryPanel.aspx?Tenant=C%26E&Query=PFZQUT48TEZPPkZhbHNlPC9MRk8%2bPElEPkZhbHNlPC9JRD48RUxDPkZhbHNlPC9FTEM%2bPEFNUD5GYWxzZTwvQU1QPjxTT0hSSVI%2bRmFsc2U8L1NPSFJJUj48U0hSUD5GYWxzZTwvU0hSUD48U0FUTz5GYWxzZTwvU0FUTz48U0FMTz5UcnVlPC9TQUxPPjxRRT4%2bMjwvUUU%2bPFFUPj48UVIgSWQ9IjEiIENQSUQ9IjAiPkN1cnJlbnQ7RmlsZXM7SG9zdCBDb250ZW50IFN0b3JlO0VxdWFsO0xBQl9QTC0zMDBUMDA8L1FSPjxRUiBJZD0iMiIgQ1BJRD0iMCI%2bYW5kO0N1cnJlbnQ7TG9jRmlsZXM7TGFuZ3VhZ2U7RXF1YWw7Q2hpbmVzZSAoU2ltcGxpZmllZCk8L1FSPjxRUiBJZD0iMyIgQ1BJRD0iMCI%2bYW5kO0N1cnJlbnQ7RmlsZXM7SG9zdCBGaWxlIFJlZmVyZW5jZTtFcXVhbDtodHRwczovL2dpdGh1Yi5jb20vTWljcm9zb2Z0TGVhcm5pbmcvUEwtMzAwLU1pY3Jvc29mdC1Qb3dlci1CSS1EYXRhLUFuYWx5c3QvYmxvYi9NYWluL3JlYWRtZS5tZDwvUVI%2bPC9RVD48Ukc%2bPEdDPk5VTEw8L0dDPjwvUkc%2bPC9WUFE%2b)

**Comment by stonezy123** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/49666210/177907240-363dfcb6-cd65-4bf0-b001-0f2789b30c0d.png)
