### ISSUE TITLE
readme.md

### ISSUE THREAD

**Issue by VietTran0302** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst.zh-cn#2]
English:
Check out the GitHub Page

Current Translation:
查看GitHub 页面

Suggested Translation:
查看 GitHub 页面

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by stonezy123** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/49666210/177907308-611ad2ad-7f9e-4be5-891c-e9306d0c071d.png)
