### ISSUE TITLE
Title of lesson 8 & 9 in lesson 8 & 9 not the same_order of lesson 8 and lesson 9 should reverse_Power BI service web page hasn’t updated "get data" button  リンク 【开源社区】如何提交你的Pull Request (附带有测试学习用的gith...、Zuo, Gongdan/左 宫丹 が作成

### ISSUE THREAD

**Issue by starmiyagarden** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst.zh-cn#46]
First, please notice the title of lesson 8 and lesson 9. 
I think the right title of lesson 8 in lesson 8 is “使用AI视觉对象分析数据”.
I think the right title of lesson 9 in lesson 9 is “创建Power BI面板”.
Because all the other lessons of the title of lesson 8 and lesson 9 are these.
But the meaning is almost the same, it’s just that all the titles should the same. Why they’re not the same?

![first](https://user-images.githubusercontent.com/131736768/234738844-00871bab-ce33-41ee-b837-c6919465e832.JPG)

Second, I think the order of lesson 8 and lesson 9 should reverse.
Look at this picture. It’s in task2 in lesson 8.
It is said that “如果你已在”创建Power BI 仪表板”实验室中发布了数据集”, 
this sentence explains that I’ve already studied the lesson 9. Please try to translate this sentence, you will know it.
But it must update the lab files synchronously. If it has too much troubles, maintain the status quo may be ok.

![second](https://user-images.githubusercontent.com/131736768/234738944-949b83f6-787e-43d9-b0c2-ab75daf730a8.JPG)

如果你已在“创建Power BI仪表板”实验室中发布了数据集
→
Please try to translate this sentence

Third, in task2 of lesson 8, when creating a dataset, I couldn’t find the “get data” in bottom left of Power BI service web page.
I ask the Power BI teacher, the teacher gave me the English version course. The Simplified Chinese version manual of lesson 8 hasn’t updated. 
The wrong one is the left picture below, the right one is the right picture below.

![third1](https://user-images.githubusercontent.com/131736768/234739261-c8be43cb-f5d2-482b-bb85-7c723df6816b.JPG)

The English version is here, but 3.is navigate to D:\PL300\Labs\08-perform-data-analysis-in-power-bi-desktop\Solution folder, 4. Is select the Sales Exploration.pbix file.

![third2](https://user-images.githubusercontent.com/131736768/234739691-c1c038e8-2963-48ff-b554-5b65e4802170.JPG)

Fourth, task 3 of lesson 9, the same as the third.

![fourth](https://user-images.githubusercontent.com/131736768/234739970-6e6adb63-8042-4bac-acc4-d5caed2632ee.JPG)

3. is navigate to D:\PL300\Labs\09-create-power-bi-dashboard\Starter folder, 4. Is select the Sales Analysis.pbix file.

If any need, please contact me. My E-Mail is cbd_zuogongdan@fujitsu.com.
Thanks very much!

Best Regards,  
Gongdan, Zuo

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by chriscarty00** [comment]
Will need WLL PM take on Page titles and layout

**Comment by chriscarty00** [comment]
Pages have been updated two months ago - not sure this is repro anymore - I cannot see it.

**Comment by stonezy123** [comment]
The loc repo up to date, please help check again and if repo, please open new issue to track.
