### ISSUE TITLE
Missing images for all labs in github.io page

### ISSUE THREAD

**Issue by lettucebo** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst.zh-cn#47]
Images are missing in every github.io page for ZH-CN labs

![image](https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst.zh-cn/assets/891383/47f7edaf-e4a2-49d1-8dff-0aba360aefbe)

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by stonezy123** [comment]
I haven't reproduced the problem.
https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst.zh-cn/blob/OLPRODLOC/Instructions/01-prepare-data-with-power-query-in-power-bi-desktop.md
![image](https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst.zh-cn/assets/49666210/301df9a7-f425-4401-870d-5474d7063976)
